version: '3.8'

services:
  prometheus:
    image: prom/prometheus:v2.51.0
    container_name: toget-prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped

  grafana:
    image: grafana/grafana:10.4.0
    container_name: toget-grafana
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
      - loki
      - tempo
    restart: unless-stopped

  loki:
    image: grafana/loki:3.0.0
    container_name: toget-loki
    volumes:
      - ./loki-config.yaml:/etc/loki/loki-config.yaml
    command: -config.file=/etc/loki/loki-config.yaml
    ports:
      - "3100:3100"
    restart: unless-stopped

  tempo:
    image: grafana/tempo:2.4.1
    container_name: toget-tempo
    volumes:
      - ./tempo-config.yaml:/etc/tempo/tempo-config.yaml
    command: -config.file=/etc/tempo/tempo-config.yaml
    ports:
      - "3200:3200" # tempo web / http API
      - "4317:4317" # otlp grpc
      - "4318:4318" # otlp http
      - "9411:9411" # zipkin
    restart: unless-stopped
